// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqetlzgepolalrmtncik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxZXRsemdlcG9sYWxybXRuY2lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5MDc3MzAsImV4cCI6MjA3NjQ4MzczMH0.BI53vCPbbJSSh7ob5UjC_QlZktwW5JZRoFfcU3vo7_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});